In [69]:
import pandas as pd
RA_White=pd.read_csv('../../Obstetric accessibility visualization/Georgia/WhiteRace.csv')

In [70]:
RA_White.head()
columns_list = RA_White.columns.tolist()

print(columns_list)

['GEO_ID', 'NAME', 'B01001A_001E', 'B01001A_001EA', 'B01001A_001M', 'B01001A_001MA', 'B01001A_002E', 'B01001A_002EA', 'B01001A_002M', 'B01001A_002MA', 'B01001A_003E', 'B01001A_003M', 'B01001A_003MA', 'B01001A_003EA', 'B01001A_004E', 'B01001A_004M', 'B01001A_004MA', 'B01001A_004EA', 'B01001A_005E', 'B01001A_005M', 'B01001A_005MA', 'B01001A_005EA', 'B01001A_006E', 'B01001A_006EA', 'B01001A_006M', 'B01001A_006MA', 'B01001A_007E', 'B01001A_007EA', 'B01001A_007M', 'B01001A_007MA', 'B01001A_008E', 'B01001A_008EA', 'B01001A_008M', 'B01001A_008MA', 'B01001A_009E', 'B01001A_009EA', 'B01001A_009M', 'B01001A_009MA', 'B01001A_010E', 'B01001A_010EA', 'B01001A_010M', 'B01001A_010MA', 'B01001A_011E', 'B01001A_011M', 'B01001A_011MA', 'B01001A_011EA', 'B01001A_012E', 'B01001A_012EA', 'B01001A_012M', 'B01001A_012MA', 'B01001A_013E', 'B01001A_013EA', 'B01001A_013M', 'B01001A_013MA', 'B01001A_014E', 'B01001A_014EA', 'B01001A_014M', 'B01001A_014MA', 'B01001A_015E', 'B01001A_015EA', 'B01001A_015M', 'B01001A_015MA', 'B01001A_016E', 'B01001A_016M', 'B01001A_016MA', 'B01001A_016EA', 'B01001A_017E', 'B01001A_017M', 'B01001A_017MA', 'B01001A_017EA', 'B01001A_018E', 'B01001A_018EA', 'B01001A_018M', 'B01001A_018MA', 'B01001A_019E', 'B01001A_019EA', 'B01001A_019M', 'B01001A_019MA', 'B01001A_020E', 'B01001A_020EA', 'B01001A_020M', 'B01001A_020MA', 'B01001A_021E', 'B01001A_021EA', 'B01001A_021M', 'B01001A_021MA', 'B01001A_022E', 'B01001A_022M', 'B01001A_022MA', 'B01001A_022EA', 'B01001A_023E', 'B01001A_023EA', 'B01001A_023M', 'B01001A_023MA', 'B01001A_024E', 'B01001A_024EA', 'B01001A_024M', 'B01001A_024MA', 'B01001A_025E', 'B01001A_025EA', 'B01001A_025M', 'B01001A_025MA', 'B01001A_026E', 'B01001A_026M', 'B01001A_026MA', 'B01001A_026EA', 'B01001A_027E', 'B01001A_027M', 'B01001A_027MA', 'B01001A_027EA', 'B01001A_028E', 'B01001A_028EA', 'B01001A_028M', 'B01001A_028MA', 'B01001A_029E', 'B01001A_029EA', 'B01001A_029M', 'B01001A_029MA', 'B01001A_030E', 'B01001A_030M', 'B01001A_030MA', 'B01001A_030EA', 'B01001A_031E', 'B01001A_031EA', 'B01001A_031M', 'B01001A_031MA', 'Unnamed: 126']

In [71]:
RA_White.rename(columns=RA_White.iloc[0], inplace=True)
RA_White_df = RA_White[[
    'Geographic Area Name',
    'Estimate!!Total!!Female!!18 and 19 years',
    'Estimate!!Total!!Female!!20 to 24 years',
    'Estimate!!Total!!Female!!25 to 29 years',
    'Estimate!!Total!!Female!!30 to 34 years',
    'Estimate!!Total!!Female!!35 to 44 years',
]]
RA_White_df_copy = RA_White_df.copy()
RA_White_df_copy.drop(RA_White_df.index[0], inplace=True)
RA_White_df_copy = RA_White_df_copy.set_index('Geographic Area Name')
RA_White_df_copy = RA_White_df_copy.iloc[1:]
RA_White_df_copy = RA_White_df_copy.astype(int)
RA_White_df_copy['Total Female, 18-44'] = RA_White_df_copy.iloc[:, 1:8].sum(axis=1)
RA_White_df_copy = RA_White_df_copy.iloc[:, -1:]
RA_White_df_copy = RA_White_df_copy.rename(columns={'Total Female, 18-44': 'Total White Female, 18-44'})
RA_White_df_copy

                                             Total White Female, 18-44
Geographic Area Name
Census Tract 9502, Appling County, Georgia                         360
Census Tract 9503, Appling County, Georgia                         608
Census Tract 9504, Appling County, Georgia                         169
Census Tract 9505, Appling County, Georgia                         541
Census Tract 9601, Atkinson County, Georgia                        146
...                                                                ...
Census Tract 9501, Worth County, Georgia                           290
Census Tract 9502, Worth County, Georgia                           824
Census Tract 9504, Worth County, Georgia                           399
Census Tract 9505, Worth County, Georgia                           257
Census Tract 9506, Worth County, Georgia                           213

[1968 rows x 1 columns]

In [72]:
RA_HispanicORlatino=pd.read_csv('../../Obstetric accessibility visualization/Georgia/HispanicorLatino.csv')

In [73]:
RA_HispanicORlatino.rename(columns=RA_HispanicORlatino.iloc[0], inplace=True)
RA_HispanicORlatino_df = RA_HispanicORlatino[[
    'Geographic Area Name',
    'Estimate!!Total!!Female!!18 and 19 years',
    'Estimate!!Total!!Female!!20 to 24 years',
    'Estimate!!Total!!Female!!25 to 29 years',
    'Estimate!!Total!!Female!!30 to 34 years',
    'Estimate!!Total!!Female!!35 to 44 years',
]]
RA_HispanicORlatino_df_copy = RA_HispanicORlatino_df.copy()
RA_HispanicORlatino_df_copy.drop(RA_HispanicORlatino_df.index[0], inplace=True)
RA_HispanicORlatino_df_copy = RA_HispanicORlatino_df_copy.set_index('Geographic Area Name')
RA_HispanicORlatino_df_copy = RA_HispanicORlatino_df_copy.iloc[1:]
RA_HispanicORlatino_df_copy = RA_HispanicORlatino_df_copy.astype(int)
RA_HispanicORlatino_df_copy['Total Female, 18-44'] = RA_HispanicORlatino_df_copy.sum(axis=1)
RA_HispanicORlatino_df_copy = RA_HispanicORlatino_df_copy[['Total Female, 18-44']]
RA_HispanicORlatino_df_copy = RA_HispanicORlatino_df_copy.rename(columns={'Total Female, 18-44': 'Total HispanicORlatino Female, 18-44'})
RA_HispanicORlatino_df_copy

                                             Total HispanicORlatino Female, 18-44
Geographic Area Name
Census Tract 9502, Appling County, Georgia                                     37
Census Tract 9503, Appling County, Georgia                                    116
Census Tract 9504, Appling County, Georgia                                     30
Census Tract 9505, Appling County, Georgia                                    138
Census Tract 9601, Atkinson County, Georgia                                    97
...                                                                           ...
Census Tract 9501, Worth County, Georgia                                        0
Census Tract 9502, Worth County, Georgia                                        0
Census Tract 9504, Worth County, Georgia                                        0
Census Tract 9505, Worth County, Georgia                                        0
Census Tract 9506, Worth County, Georgia                                       17

[1968 rows x 1 columns]

In [74]:
RA_BlackorAfricanAmerican=pd.read_csv('../../Obstetric accessibility visualization/Georgia/BlackorAfricanAmericanRace.csv')
RA_BlackorAfricanAmerican.head()

,GEO_ID,NAME,B01001B_001E,B01001B_001EA,B01001B_001M,B01001B_001MA,B01001B_002E,B01001B_002EA,B01001B_002M,B01001B_002MA,...,B01001B_029EA,B01001B_030E,B01001B_030M,B01001B_030MA,B01001B_030EA,B01001B_031E,B01001B_031M,B01001B_031MA,B01001B_031EA,Unnamed: 126
0,Geography,Geographic Area Name,Estimate!!Total,Annotation of Estimate!!Total,Margin of Error!!Total,Annotation of Margin of Error!!Total,Estimate!!Total!!Male,Annotation of Estimate!!Total!!Male,Margin of Error!!Total!!Male,Annotation of Margin of Error!!Total!!Male,...,Annotation of Estimate!!Total!!Female!!65 to 7...,Estimate!!Total!!Female!!75 to 84 years,Margin of Error!!Total!!Female!!75 to 84 years,Annotation of Margin of Error!!Total!!Female!!...,Annotation of Estimate!!Total!!Female!!75 to 8...,Estimate!!Total!!Female!!85 years and over,Margin of Error!!Total!!Female!!85 years and over,Annotation of Margin of Error!!Total!!Female!!...,Annotation of Estimate!!Total!!Female!!85 year...,NaN
1,1400000US13001950100,"Census Tract 9501, Appling County, Georgia",91,NaN,65,NaN,43,NaN,32,NaN,...,NaN,0,13,NaN,NaN,0,13,NaN,NaN,NaN
2,1400000US13001950200,"Census Tract 9502, Appling County, Georgia",1698,NaN,385,NaN,912,NaN,214,NaN,...,NaN,36,22,NaN,NaN,29,21,NaN,NaN,NaN
3,1400000US13001950300,"Census Tract 9503, Appling County, Georgia",934,NaN,382,NaN,399,NaN,185,NaN,...,NaN,0,18,NaN,NaN,18,22,NaN,NaN,NaN
4,1400000US13001950400,"Census Tract 9504, Appling County, Georgia",395,NaN,182,NaN,208,NaN,102,NaN,...,NaN,16,19,NaN,NaN,4,7,NaN,NaN,NaN

In [75]:
RA_BlackorAfricanAmerican.rename(columns=RA_BlackorAfricanAmerican.iloc[0], inplace=True)
RA_BlackorAfricanAmerican_df = RA_BlackorAfricanAmerican[[
    'Geographic Area Name',
    'Estimate!!Total!!Female!!18 and 19 years',
    'Estimate!!Total!!Female!!20 to 24 years',
    'Estimate!!Total!!Female!!25 to 29 years',
    'Estimate!!Total!!Female!!30 to 34 years',
    'Estimate!!Total!!Female!!35 to 44 years',
]]
RA_BlackorAfricanAmerican_df_copy = RA_BlackorAfricanAmerican_df.copy()
RA_BlackorAfricanAmerican_df_copy.drop(RA_BlackorAfricanAmerican_df.index[0], inplace=True)
RA_BlackorAfricanAmerican_df_copy = RA_BlackorAfricanAmerican_df_copy.set_index('Geographic Area Name')
RA_BlackorAfricanAmerican_df_copy = RA_BlackorAfricanAmerican_df_copy.iloc[1:]
RA_BlackorAfricanAmerican_df_copy = RA_BlackorAfricanAmerican_df_copy.astype(int)
RA_BlackorAfricanAmerican_df_copy['Total Female, 18-44'] = RA_BlackorAfricanAmerican_df_copy.sum(axis=1)
RA_BlackorAfricanAmerican_df_copy = RA_BlackorAfricanAmerican_df_copy[['Total Female, 18-44']]
RA_BlackorAfricanAmerican_df_copy = RA_BlackorAfricanAmerican_df_copy.rename(columns={'Total Female, 18-44': 'Total BlackorAfricanAmerican Female, 18-44'})
RA_BlackorAfricanAmerican_df_copy.head(100)

                                             Total BlackorAfricanAmerican Female, 18-44
Geographic Area Name
Census Tract 9502, Appling County, Georgia                                          233
Census Tract 9503, Appling County, Georgia                                          217
Census Tract 9504, Appling County, Georgia                                           19
Census Tract 9505, Appling County, Georgia                                           28
Census Tract 9601, Atkinson County, Georgia                                          50
...                                                                                 ...
Census Tract 132.01, Bibb County, Georgia                                          1313
Census Tract 132.02, Bibb County, Georgia                                           464
Census Tract 133.02, Bibb County, Georgia                                           789
Census Tract 134.07, Bibb County, Georgia                                           548
Census Tract 134.08, Bibb County, Georgia                                           297

[100 rows x 1 columns]

In [76]:
RA_Asian=pd.read_csv('../../Obstetric accessibility visualization/Georgia/AsianRace.csv')

In [77]:
RA_Asian.rename(columns=RA_Asian.iloc[0], inplace=True)
RA_Asian_df = RA_Asian[[
    'Geographic Area Name',
    'Estimate!!Total!!Female!!18 and 19 years',
    'Estimate!!Total!!Female!!20 to 24 years',
    'Estimate!!Total!!Female!!25 to 29 years',
    'Estimate!!Total!!Female!!30 to 34 years',
    'Estimate!!Total!!Female!!35 to 44 years',
]]
RA_Asian_df_copy = RA_Asian_df.copy()
RA_Asian_df_copy.drop(RA_Asian_df.index[0], inplace=True)
RA_Asian_df_copy = RA_Asian_df_copy.set_index('Geographic Area Name')
RA_Asian_df_copy = RA_Asian_df_copy.iloc[1:]
RA_Asian_df_copy = RA_Asian_df_copy.astype(int)
RA_Asian_df_copy['Total Female, 18-44'] = RA_Asian_df_copy.sum(axis=1)
RA_Asian_df_copy = RA_Asian_df_copy[['Total Female, 18-44']]
RA_Asian_df_copy = RA_Asian_df_copy.rename(columns={'Total Female, 18-44': 'Total Asian Female, 18-44'})
RA_Asian_df_copy

                                             Total Asian Female, 18-44
Geographic Area Name
Census Tract 9502, Appling County, Georgia                           0
Census Tract 9503, Appling County, Georgia                          29
Census Tract 9504, Appling County, Georgia                           0
Census Tract 9505, Appling County, Georgia                           0
Census Tract 9601, Atkinson County, Georgia                          0
...                                                                ...
Census Tract 9501, Worth County, Georgia                            10
Census Tract 9502, Worth County, Georgia                             0
Census Tract 9504, Worth County, Georgia                            12
Census Tract 9505, Worth County, Georgia                             9
Census Tract 9506, Worth County, Georgia                             0

[1968 rows x 1 columns]

In [78]:
RA_AmericanIndianORAlaskaNative=pd.read_csv('../../Obstetric accessibility visualization/Georgia/AmericanIndian&AlaskaNative.csv')

In [79]:
RA_AmericanIndianORAlaskaNative.rename(columns=RA_AmericanIndianORAlaskaNative.iloc[0], inplace=True)
RA_AmericanIndianORAlaskaNative_df = RA_AmericanIndianORAlaskaNative[[
    'Geographic Area Name',
    'Estimate!!Total!!Female!!18 and 19 years',
    'Estimate!!Total!!Female!!20 to 24 years',
    'Estimate!!Total!!Female!!25 to 29 years',
    'Estimate!!Total!!Female!!30 to 34 years',
    'Estimate!!Total!!Female!!35 to 44 years',
]]
RA_AmericanIndianORAlaskaNative_df_copy = RA_AmericanIndianORAlaskaNative_df.copy()
RA_AmericanIndianORAlaskaNative_df_copy.drop(RA_AmericanIndianORAlaskaNative_df.index[0], inplace=True)
RA_AmericanIndianORAlaskaNative_df_copy = RA_AmericanIndianORAlaskaNative_df_copy.set_index('Geographic Area Name')
RA_AmericanIndianORAlaskaNative_df_copy = RA_AmericanIndianORAlaskaNative_df_copy.iloc[1:]
RA_AmericanIndianORAlaskaNative_df_copy = RA_AmericanIndianORAlaskaNative_df_copy.astype(int)
RA_AmericanIndianORAlaskaNative_df_copy['Total Female, 18-44'] = RA_AmericanIndianORAlaskaNative_df_copy.sum(axis=1)
RA_AmericanIndianORAlaskaNative_df_copy = RA_AmericanIndianORAlaskaNative_df_copy[['Total Female, 18-44']]
RA_AmericanIndianORAlaskaNative_df_copy = RA_AmericanIndianORAlaskaNative_df_copy.rename(columns={'Total Female, 18-44': 'Total AmericanIndianORAlaskaNative Female, 18-44'})
RA_AmericanIndianORAlaskaNative_df_copy

                                             Total AmericanIndianORAlaskaNative Female, 18-44
Geographic Area Name
Census Tract 9502, Appling County, Georgia                                                 22
Census Tract 9503, Appling County, Georgia                                                  0
Census Tract 9504, Appling County, Georgia                                                  0
Census Tract 9505, Appling County, Georgia                                                  0
Census Tract 9601, Atkinson County, Georgia                                                 0
...                                                                                       ...
Census Tract 9501, Worth County, Georgia                                                    0
Census Tract 9502, Worth County, Georgia                                                    0
Census Tract 9504, Worth County, Georgia                                                    0
Census Tract 9505, Worth County, Georgia                                                    0
Census Tract 9506, Worth County, Georgia                                                   17

[1968 rows x 1 columns]

In [80]:
RA_NativeHawaiinOtherPacificIslander=pd.read_csv('../../Obstetric accessibility visualization/Georgia/NativeHawaiin&OtherPacificIslander.csv')

In [81]:
RA_NativeHawaiinOtherPacificIslander.rename(columns=RA_NativeHawaiinOtherPacificIslander.iloc[0], inplace=True)
RA_NativeHawaiinOtherPacificIslander_df = RA_NativeHawaiinOtherPacificIslander[[
    'Geographic Area Name',
    'Estimate!!Total!!Female!!18 and 19 years',
    'Estimate!!Total!!Female!!20 to 24 years',
    'Estimate!!Total!!Female!!25 to 29 years',
    'Estimate!!Total!!Female!!30 to 34 years',
    'Estimate!!Total!!Female!!35 to 44 years',
]]
RA_NativeHawaiinOtherPacificIslander_df_copy = RA_NativeHawaiinOtherPacificIslander_df.copy()
RA_NativeHawaiinOtherPacificIslander_df_copy.drop(RA_NativeHawaiinOtherPacificIslander_df.index[0], inplace=True)
RA_NativeHawaiinOtherPacificIslander_df_copy = RA_NativeHawaiinOtherPacificIslander_df_copy.set_index('Geographic Area Name')
RA_NativeHawaiinOtherPacificIslander_df_copy = RA_NativeHawaiinOtherPacificIslander_df_copy.iloc[1:]
RA_NativeHawaiinOtherPacificIslander_df_copy = RA_NativeHawaiinOtherPacificIslander_df_copy.astype(int)
RA_NativeHawaiinOtherPacificIslander_df_copy['Total Female, 18-44'] = RA_NativeHawaiinOtherPacificIslander_df_copy.sum(axis=1)
RA_NativeHawaiinOtherPacificIslander_df_copy = RA_NativeHawaiinOtherPacificIslander_df_copy[['Total Female, 18-44']]
RA_NativeHawaiinOtherPacificIslander_df_copy = RA_NativeHawaiinOtherPacificIslander_df_copy.rename(columns={'Total Female, 18-44': 'Total NativeHawaiin&OtherPacificIslander Female, 18-44'})
RA_NativeHawaiinOtherPacificIslander_df_copy

                                             Total NativeHawaiin&OtherPacificIslander Female, 18-44
Geographic Area Name
Census Tract 9502, Appling County, Georgia                                                   0
Census Tract 9503, Appling County, Georgia                                                   0
Census Tract 9504, Appling County, Georgia                                                   0
Census Tract 9505, Appling County, Georgia                                                   0
Census Tract 9601, Atkinson County, Georgia                                                  0
...                                                                                        ...
Census Tract 9501, Worth County, Georgia                                                     0
Census Tract 9502, Worth County, Georgia                                                     0
Census Tract 9504, Worth County, Georgia                                                     0
Census Tract 9505, Worth County, Georgia                                                     0
Census Tract 9506, Worth County, Georgia                                                     0

[1968 rows x 1 columns]

In [82]:
merged_df = RA_AmericanIndianORAlaskaNative_df_copy.merge(RA_BlackorAfricanAmerican_df_copy, on='Geographic Area Name').merge(RA_HispanicORlatino_df_copy, on='Geographic Area Name').merge(RA_White_df_copy, on='Geographic Area Name').merge(RA_Asian_df_copy, on='Geographic Area Name').merge(RA_NativeHawaiinOtherPacificIslander_df_copy, on='Geographic Area Name')
merged_df

,"Total AmericanIndianORAlaskaNative Female, 18-44","Total BlackorAfricanAmerican Female, 18-44","Total HispanicORlatino Female, 18-44","Total White Female, 18-44","Total Asian Female, 18-44","Total NativeHawaiin&OtherPacificIslander Female, 18-44"
Geographic Area Name,,,,,,
"Census Tract 9502, Appling County, Georgia",22,233,37,360,0,0
"Census Tract 9503, Appling County, Georgia",0,217,116,608,29,0
"Census Tract 9504, Appling County, Georgia",0,19,30,169,0,0
"Census Tract 9505, Appling County, Georgia",0,28,138,541,0,0
"Census Tract 9601, Atkinson County, Georgia",0,50,97,146,0,0
...,...,...,...,...,...,...
"Census Tract 9501, Worth County, Georgia",0,85,0,290,10,0
"Census Tract 9502, Worth County, Georgia",0,426,0,824,0,0
"Census Tract 9504, Worth County, Georgia",0,139,0,399,12,0
"Census Tract 9505, Worth County, Georgia",0,446,0,257,9,0
"Census Tract 9506, Worth County, Georgia",17,31,17,213,0,0

In [83]:
def calculate_proportions(row):
    row_sum = row.sum()
    if row_sum != 0:
        return row / row_sum
    else:
        return row

# Apply the function to each row
proportion_df = merged_df.apply(calculate_proportions, axis=1)

# Display the resulting DataFrame
proportion_df
#

,"Total AmericanIndianORAlaskaNative Female, 18-44","Total BlackorAfricanAmerican Female, 18-44","Total HispanicORlatino Female, 18-44","Total White Female, 18-44","Total Asian Female, 18-44","Total NativeHawaiin&OtherPacificIslander Female, 18-44"
Geographic Area Name,,,,,,
"Census Tract 9502, Appling County, Georgia",0.033742,0.357362,0.056748,0.552147,0.000000,0.0
"Census Tract 9503, Appling County, Georgia",0.000000,0.223711,0.119588,0.626804,0.029897,0.0
"Census Tract 9504, Appling County, Georgia",0.000000,0.087156,0.137615,0.775229,0.000000,0.0
"Census Tract 9505, Appling County, Georgia",0.000000,0.039604,0.195191,0.765205,0.000000,0.0
"Census Tract 9601, Atkinson County, Georgia",0.000000,0.170648,0.331058,0.498294,0.000000,0.0
...,...,...,...,...,...,...
"Census Tract 9501, Worth County, Georgia",0.000000,0.220779,0.000000,0.753247,0.025974,0.0
"Census Tract 9502, Worth County, Georgia",0.000000,0.340800,0.000000,0.659200,0.000000,0.0
"Census Tract 9504, Worth County, Georgia",0.000000,0.252727,0.000000,0.725455,0.021818,0.0
"Census Tract 9505, Worth County, Georgia",0.000000,0.626404,0.000000,0.360955,0.012640,0.0
"Census Tract 9506, Worth County, Georgia",0.061151,0.111511,0.061151,0.766187,0.000000,0.0

In [84]:
proportion_df=proportion_df.reset_index()


proportion_df

,Geographic Area Name,"Total AmericanIndianORAlaskaNative Female, 18-44","Total BlackorAfricanAmerican Female, 18-44","Total HispanicORlatino Female, 18-44","Total White Female, 18-44","Total Asian Female, 18-44","Total NativeHawaiin&OtherPacificIslander Female, 18-44"
0,"Census Tract 9502, Appling County, Georgia",0.033742,0.357362,0.056748,0.552147,0.000000,0.0
1,"Census Tract 9503, Appling County, Georgia",0.000000,0.223711,0.119588,0.626804,0.029897,0.0
2,"Census Tract 9504, Appling County, Georgia",0.000000,0.087156,0.137615,0.775229,0.000000,0.0
3,"Census Tract 9505, Appling County, Georgia",0.000000,0.039604,0.195191,0.765205,0.000000,0.0
4,"Census Tract 9601, Atkinson County, Georgia",0.000000,0.170648,0.331058,0.498294,0.000000,0.0
...,...,...,...,...,...,...,...
1963,"Census Tract 9501, Worth County, Georgia",0.000000,0.220779,0.000000,0.753247,0.025974,0.0
1964,"Census Tract 9502, Worth County, Georgia",0.000000,0.340800,0.000000,0.659200,0.000000,0.0
1965,"Census Tract 9504, Worth County, Georgia",0.000000,0.252727,0.000000,0.725455,0.021818,0.0
1966,"Census Tract 9505, Worth County, Georgia",0.000000,0.626404,0.000000,0.360955,0.012640,0.0
1967,"Census Tract 9506, Worth County, Georgia",0.061151,0.111511,0.061151,0.766187,0.000000,0.0

In [85]:
import pandas as pd
RA_Georgia_BG=pd.read_csv('../../Obstetric accessibility visualization/Indiana/RA_NativeHawaiin_censusTract.csv')
RA_Georgia_BG.head()
RA_Georgia_BG.rename(columns=RA_Georgia_BG.iloc[0], inplace=True)
RA_Georgia_BG.columns
RA_Georgia_BG_df = RA_Georgia_BG[[
    'Geographic Area Name',
    'Estimate!!Total!!Female!!18 and 19 years',
    'Estimate!!Total!!Female!!20 years',
    'Estimate!!Total!!Female!!22 to 24 years',
    'Estimate!!Total!!Female!!25 to 29 years',
    'Estimate!!Total!!Female!!30 to 34 years',
    'Estimate!!Total!!Female!!30 to 34 years',
    'Estimate!!Total!!Female!!35 to 39 years',
    'Estimate!!Total!!Female!!40 to 44 years'
]]

RA_Georgia_BG_df_copy = RA_Georgia_BG_df.copy()
RA_Georgia_BG_df_copy.drop(RA_Georgia_BG_df.index[0], inplace=True)
age_columns = [
    'Estimate!!Total!!Female!!18 and 19 years',
    'Estimate!!Total!!Female!!20 years',
    'Estimate!!Total!!Female!!22 to 24 years',
    'Estimate!!Total!!Female!!25 to 29 years',
    'Estimate!!Total!!Female!!30 to 34 years',
    'Estimate!!Total!!Female!!30 to 34 years',
    'Estimate!!Total!!Female!!35 to 39 years',
    'Estimate!!Total!!Female!!40 to 44 years'
]

RA_Georgia_BG_df_copy

,Geographic Area Name,Estimate!!Total!!Female!!18 and 19 years,Estimate!!Total!!Female!!20 years,Estimate!!Total!!Female!!22 to 24 years,Estimate!!Total!!Female!!25 to 29 years,Estimate!!Total!!Female!!30 to 34 years,Estimate!!Total!!Female!!30 to 34 years,Estimate!!Total!!Female!!35 to 39 years,Estimate!!Total!!Female!!40 to 44 years
1,"Block Group 1, Census Tract 9501, Appling Coun...",0,0,44,16,0,0,13,55
2,"Block Group 2, Census Tract 9501, Appling Coun...",39,0,0,19,55,55,69,64
3,"Block Group 1, Census Tract 9502, Appling Coun...",28,19,27,89,53,53,56,37
4,"Block Group 2, Census Tract 9502, Appling Coun...",23,29,5,5,28,28,30,30
5,"Block Group 3, Census Tract 9502, Appling Coun...",22,9,0,57,24,24,11,0
...,...,...,...,...,...,...,...,...,...
5529,"Block Group 1, Census Tract 9505, Worth County...",5,0,21,52,58,58,21,45
5530,"Block Group 2, Census Tract 9505, Worth County...",26,22,11,23,90,90,22,40
5531,"Block Group 3, Census Tract 9505, Worth County...",0,0,56,45,0,0,17,88
5532,"Block Group 1, Census Tract 9506, Worth County...",4,0,50,21,45,45,31,35
5533,"Block Group 2, Census Tract 9506, Worth County...",0,0,0,25,6,6,6,24

<h2> RA_Count_BG_level </h2>

In [86]:
for col in age_columns:
    if col in RA_Georgia_BG_df_copy.columns:
        RA_Georgia_BG_df_copy[col] = RA_Georgia_BG_df_copy[col].astype(str)  # Ensure it's a string
        RA_Georgia_BG_df_copy[col] = RA_Georgia_BG_df_copy[col].apply(lambda x: pd.to_numeric(x, errors='coerce'))

# Create the new column by summing the specified columns
RA_Georgia_BG_df_copy['Total Female Age 18-44 years'] = RA_Georgia_BG_df_copy[age_columns].sum(axis=1)

# Drop all other columns except 'Geographic Area Name' and the new column
RA_Georgia_BG_df_copy = RA_Georgia_BG_df_copy[['Geographic Area Name', 'Total Female Age 18-44 years']]
RA_Georgia_BG_df_copy.rename(columns={'Geographic Area Name': 'Geographic Area Names'}, inplace=True)
# Display the resulting DataFrame
RA_Georgia_BG_df_copy

RA_Georgia_BG_df_copy['Geographic Area Name'] = RA_Georgia_BG_df_copy['Geographic Area Names'].str.extract(r'Block Group \d+, (.*)')

RA_Georgia_BG_df_copy.head()

/var/folders/_2/chm4htkx0yj_5655k61rx6tc0000gn/T/ipykernel_76635/1838968070.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RA_Georgia_BG_df_copy.rename(columns={'Geographic Area Name': 'Geographic Area Names'}, inplace=True)
/var/folders/_2/chm4htkx0yj_5655k61rx6tc0000gn/T/ipykernel_76635/1838968070.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  RA_Georgia_BG_df_copy['Geographic Area Name'] = RA_Georgia_BG_df_copy['Geographic Area Names'].str.extract(r'Block Group \d+, (.*)')

,Geographic Area Names,Total Female Age 18-44 years,Geographic Area Name
1,"Block Group 1, Census Tract 9501, Appling Coun...",128,"Census Tract 9501, Appling County, Georgia"
2,"Block Group 2, Census Tract 9501, Appling Coun...",411,"Census Tract 9501, Appling County, Georgia"
3,"Block Group 1, Census Tract 9502, Appling Coun...",468,"Census Tract 9502, Appling County, Georgia"
4,"Block Group 2, Census Tract 9502, Appling Coun...",234,"Census Tract 9502, Appling County, Georgia"
5,"Block Group 3, Census Tract 9502, Appling Coun...",195,"Census Tract 9502, Appling County, Georgia"

In [87]:
merged_df = pd.merge(RA_Georgia_BG_df_copy, proportion_df, on='Geographic Area Name')
merged_df.head()

,Geographic Area Names,Total Female Age 18-44 years,Geographic Area Name,"Total AmericanIndianORAlaskaNative Female, 18-44","Total BlackorAfricanAmerican Female, 18-44","Total HispanicORlatino Female, 18-44","Total White Female, 18-44","Total Asian Female, 18-44","Total NativeHawaiin&OtherPacificIslander Female, 18-44"
0,"Block Group 1, Census Tract 9502, Appling Coun...",468,"Census Tract 9502, Appling County, Georgia",0.033742,0.357362,0.056748,0.552147,0.000000,0.0
1,"Block Group 2, Census Tract 9502, Appling Coun...",234,"Census Tract 9502, Appling County, Georgia",0.033742,0.357362,0.056748,0.552147,0.000000,0.0
2,"Block Group 3, Census Tract 9502, Appling Coun...",195,"Census Tract 9502, Appling County, Georgia",0.033742,0.357362,0.056748,0.552147,0.000000,0.0
3,"Block Group 1, Census Tract 9503, Appling Coun...",328,"Census Tract 9503, Appling County, Georgia",0.000000,0.223711,0.119588,0.626804,0.029897,0.0
4,"Block Group 2, Census Tract 9503, Appling Coun...",537,"Census Tract 9503, Appling County, Georgia",0.000000,0.223711,0.119588,0.626804,0.029897,0.0

In [88]:
columns_to_multiply = [
    'Total AmericanIndianORAlaskaNative Female, 18-44',
       'Total BlackorAfricanAmerican Female, 18-44',
       'Total HispanicORlatino Female, 18-44', 'Total White Female, 18-44',
       'Total Asian Female, 18-44',
       'Total NativeHawaiin&OtherPacificIslander Female, 18-44'
]

# Performing the multiplication
for column in columns_to_multiply:
    merged_df[column] = (merged_df[column] * merged_df['Total Female Age 18-44 years'])

# Display the modified DataFrame
merged_df

,Geographic Area Names,Total Female Age 18-44 years,Geographic Area Name,"Total AmericanIndianORAlaskaNative Female, 18-44","Total BlackorAfricanAmerican Female, 18-44","Total HispanicORlatino Female, 18-44","Total White Female, 18-44","Total Asian Female, 18-44","Total NativeHawaiin&OtherPacificIslander Female, 18-44"
0,"Block Group 1, Census Tract 9502, Appling Coun...",468,"Census Tract 9502, Appling County, Georgia",15.791411,167.245399,26.558282,258.404908,0.000000,0.0
1,"Block Group 2, Census Tract 9502, Appling Coun...",234,"Census Tract 9502, Appling County, Georgia",7.895706,83.622699,13.279141,129.202454,0.000000,0.0
2,"Block Group 3, Census Tract 9502, Appling Coun...",195,"Census Tract 9502, Appling County, Georgia",6.579755,69.685583,11.065951,107.668712,0.000000,0.0
3,"Block Group 1, Census Tract 9503, Appling Coun...",328,"Census Tract 9503, Appling County, Georgia",0.000000,73.377320,39.224742,205.591753,9.806186,0.0
4,"Block Group 2, Census Tract 9503, Appling Coun...",537,"Census Tract 9503, Appling County, Georgia",0.000000,120.132990,64.218557,336.593814,16.054639,0.0
...,...,...,...,...,...,...,...,...,...
5526,"Block Group 1, Census Tract 9505, Worth County...",376,"Census Tract 9505, Worth County, Georgia",0.000000,235.528090,0.000000,135.719101,4.752809,0.0
5527,"Block Group 2, Census Tract 9505, Worth County...",504,"Census Tract 9505, Worth County, Georgia",0.000000,315.707865,0.000000,181.921348,6.370787,0.0
5528,"Block Group 3, Census Tract 9505, Worth County...",206,"Census Tract 9505, Worth County, Georgia",0.000000,129.039326,0.000000,74.356742,2.603933,0.0
5529,"Block Group 1, Census Tract 9506, Worth County...",321,"Census Tract 9506, Worth County, Georgia",19.629496,35.794964,19.629496,245.946043,0.000000,0.0
5530,"Block Group 2, Census Tract 9506, Worth County...",79,"Census Tract 9506, Worth County, Georgia",4.830935,8.809353,4.830935,60.528777,0.000000,0.0

In [89]:
columns_to_round = [
    'Total AmericanIndianORAlaskaNative Female, 18-44',
       'Total BlackorAfricanAmerican Female, 18-44',
       'Total HispanicORlatino Female, 18-44', 'Total White Female, 18-44',
       'Total Asian Female, 18-44',
       'Total NativeHawaiin&OtherPacificIslander Female, 18-44'
]

for index, row in merged_df.iterrows():
    # Round all but the last value
    for column in columns_to_round[:-1]:
        merged_df.at[index, column] = round(row[column])
    
    # Calculate the last value to ensure the sum matches the Population
    last_column = columns_to_round[-1]
    merged_df.at[index, last_column] = row['Total Female Age 18-44 years'] - sum([round(row[col]) for col in columns_to_round[:-1]])
    
merged_df.drop('Geographic Area Name', axis=1, inplace=True)

In [90]:
merged_df.head()

,Geographic Area Names,Total Female Age 18-44 years,"Total AmericanIndianORAlaskaNative Female, 18-44","Total BlackorAfricanAmerican Female, 18-44","Total HispanicORlatino Female, 18-44","Total White Female, 18-44","Total Asian Female, 18-44","Total NativeHawaiin&OtherPacificIslander Female, 18-44"
0,"Block Group 1, Census Tract 9502, Appling Coun...",468,16.0,167.0,27.0,258.0,0.0,0.0
1,"Block Group 2, Census Tract 9502, Appling Coun...",234,8.0,84.0,13.0,129.0,0.0,0.0
2,"Block Group 3, Census Tract 9502, Appling Coun...",195,7.0,70.0,11.0,108.0,0.0,-1.0
3,"Block Group 1, Census Tract 9503, Appling Coun...",328,0.0,73.0,39.0,206.0,10.0,0.0
4,"Block Group 2, Census Tract 9503, Appling Coun...",537,0.0,120.0,64.0,337.0,16.0,0.0

In [93]:
import os
os.chdir()

'/Users/ayushigoyal/Obstetric accessibility visualization/Georgia'

In [ ]:
merged_df.to_csv('Distribution_across_Race.csv', index=False)